#==============================O==============================#
# I---------------------------------------------------------I #
# |    Advanced Achievements 2.3.2 configuration - Readme   | #
# 1---------------------------------------------------------1 #
#==============================o==============================#

# You can use Minecraft chat colours in messages and names, but include ' ' around the whole text.
# If you want to use a ' in a text, write two ' instead, and include additional ' ' around the whole text.
# In command rewards, PLAYER designates the name of the player who got the achievement.
# Only spaces, no tabs. Don't forget the indents, plugin won't work otherwise! 
# To check your file, use: yaml-online-parser.appspot.com
# Available mobs for the Kills section: hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Available items for rewards/Crafts/Places/Breaks: hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Default file: dev.bukkit.org/bukkit-plugins/advanced-achievements/pages/configuration/

#=============================O=O=============================#
# II-------------------------------------------------------II #
# |                    General  settings                    | #
# 2---------------------------------------------------------2 #
#=============================o=o=============================#

# Time in seconds between each /aach book.
TimeBook: 900

# Time in seconds between each /aach list.
TimeList: 0

# Check for update on plugin launch and notify when an OP joins the game.
CheckForUpdate: true

# Set to true to activate firework effects when a player receives an achievement.
Firework: true

# Choose BALL_LARGE, BALL, BURST, CREEPER or STAR.
FireworkStyle: BALL_LARGE

# Set to true to activate particle effects when receiving book and when player in top list.
AdditionalEffects: true

# Set to true to activate sound effects when receiving book and when player in top list.
Sound: true

# Set to true if you are using a version of Vault prior to 1.4.
RetroVault: false

# Set the icon of the plugin (default: shamrock, "\u2618").
Icon: "\u2618"

# Set the color of the plugin (default: 5, dark purple).
Color: '5'

# Notify other connected players when an achievement is received.
ChatNotify: false

# Separator between name, description and date on a book page.
BookSeparator: ''

# Stop stats from increasing when player in creative mode (except Connections and PlayedTime).
RestrictCreative: false

# Stop stats from increasing when player in a specific world (delete the [] before using).
ExcludedWorlds: []
#  - yourWorld1
#  - yourWorld2

# Number of players displayed on /aach top command.
TopList: 5

# Obfuscate achievements that have not yet been received in /aach list.
ObfuscateNotReceived: true

# Hide categories with no achievements yet received in /aach list.
HideNotReceivedCategories: false

# Display achievement name and description as screen titles.
TitleScreen: true

#=============================OOO=============================#
# III-----------------------------------------------------III #
# |                    Database settings                    | #
# 3---------------------------------------------------------3 #
#=============================ooo=============================#

# DO NOT CHANGE OR DELETE.
DatabaseVersion: 0

# Make a daily backup of your local database.
DatabaseBackup: true

# Database type, sqlite or mysql.
DatabaseType: sqlite

# Settings to link with MySQL database (ignore if sqlite).
MYSQL:
  Database: 'jdbc:mysql://localhost:3306/minecraft'
  User: root
  Password: root
  
#============================OO=OO============================#
# IV-------------------------------------------------------IV #
# |                  Performance settings                   | #
# 4---------------------------------------------------------4 #
#============================oo=oo============================#

# DO NOT CHANGE THE FOLLOWING UNLESS YOU ARE AN EXPERIENCED USER. The intervals are in seconds.
# Frequency of play time checks for players. Smaller values give more precision but more CPU usage.
PlaytimeTaskInterval: 150

# Calculates distance traveled by players. Smaller values give more precision but more CPU usage.
DistanceTaskInterval: 5

# Frequency of some statistics writes to the database.
PooledRequestsTaskInterval: 60

# Enable multithreading for some statistics writes to the database.
AsyncPooledRequestsSender: true

#============================OOOOO============================#
# V---------------------------------------------------------V #
# |                  Action  achievements                   | #
# 5---------------------------------------------------------5 #
#============================ooooo============================#

# When a player connects during the day.
Connections:
  '1':
    Message: You connected to our server for the first time!
    Name: Good Choice

# When a specific block is placed (specify block name, lower case).
Places:
  stone:
    '100':
      Message: '&4One hundred placed stones!'
      Name: Stone Addict
    '1000':
      Message: '&4One thousand placed stones!'
      Name: Stone God
      
# When a specific block is broken (specify block name, lower case).
Breaks:
  stone:
    '1':
      Message: '&1The first time you went mining!'
      Name: Cobble!
      Reward:
        Command: give PLAYER 158 10; give PLAYER 126 5
  log:
    '100':
      Message: '&2You have cut 100 logs!'
      Name: Wood Cutter
              
# When a specific mob is killed (specify mob name or 'player', lower case).
Kills:
  zombie:
    '1':
      Message: '&8The first time you killed a zombie!'
      Name: The Walking Dead
      Reward:
        Money: 1         
        Item: diamond 1
          
# When a specific item is crafted (specify item name, lower case).
Crafts:
  diamond_sword:
    '1':
      Message: The first time you crafted a blade!
      Name: Blacksmith Apprentice
      Reward:
        Money: 2
      
# When the player dies.
Deaths:
  '1':
    Message: The first time you died!
    Name: Rest in Peace
    
# When an arrow is shot.
Arrows:
  '50':
    Message: '50 arrows shot!'
    Name: Arrows Around the Place
    
# When a snowball is thrown.  
Snowballs:
  '1000':
    Message: '1000 snowballs thrown. That''s the spirit!'
    Name: Winter Addict 
    
# When an egg is thrown.  
Eggs:
  '1000':
    Message: '1000 eggs thrown!'
    Name: Omelet Addict 
    
# When a fish is caught. 
Fish:
  '1':
    Message: The first time you caught a fish!
    Name: Time for Fish and Chips

# When a tool/armor/weapon is broken.  
ItemBreaks:
  '1':
    Message: You broke your favorite tool!
    Name: '&4Clumsy Guy'

# When an item is eaten.  
EatenItems:
  '1':
    Message: Just had a snack!
    Name: First Snack  
    
# When a sheep is sheared.
Shear:
  '100':
    Message: 100 sheep sheared!
    Name: '&1Wool Addict'
    
# When a cow is milked.
Milk:
  '1':
    Message: Just milked a cow!
    Name: First Milk    
    
# When a trade with a villager is made.
Trades:
  '1':
    Message: Doing business with your first villager!
    Name: First Trade    
    
# When an anvil is used.
AnvilsUsed:
  '1':
    Message: You just repaired your first item!
    Name: First Repair 
    
# When an anvil is used.
Enchantments:
  '5':
    Message: 5 objects enchanted!
    Name: '&5Wizard'
    
# When a bed is entered. 
Beds:  
  '5':
    Message: You entered a bed 5 times!
    Name: Sleepy guy 
    
# Maximum level reached.    
MaxLevel:  
  '10':
    Message: Level 10 reached!
    Name: '&4Rookie'  
    
# When a potion is consumed.
ConsumedPotions:
  '100':
    Message: Drinking weird beverages all the time...
    Name: Alcoholic 
    
# Amount of time played on the server (in hours, use integers).
PlayedTime:
  '1':
    Message: You played during one hour on the server!
    Name: First Hour
    
# When a distance is traveled by foot.
DistanceFoot:
  '1000':
    Message: You traveled 1000 blocks by foot!
    Name: Big Walker 
    
# When a distance is traveled on a pig.
DistancePig:
  '100':
    Message: You traveled 100 blocks on a pig!
    Name: Carrot on a Stick Master
    
# When a distance is traveled on a horse.
DistanceHorse:
  '500':
    Message: You traveled 500 blocks on a horse!
    Name: The Avener
    
# When a distance is traveled in a minecart.
DistanceMinecart:
  '100':
    Message: You traveled 100 blocks in a minecart!
    Name: Carting Fan
    
# When a distance is traveled in a boat.
DistanceBoat:
  '200':
    Message: You traveled 200 blocks in a boat!
    Name: Great Sailor
    
# When an item is dropped on the ground.
ItemDrops:
  '15':
    Message: You're killing the planet!
    Name: Polluter
    
# When soil is plowed with a hoe.
HoePlowings:
  '10':
    Message: You plowed the ground 10 times!
    Name: Farmer
    Reward:                 
        Item: cookie 15
    
# When bone meal is used to fertilise plants.
Fertilising:
  '15':
    Message: You used bone meal on plants 15 times!
    Name: Gardener
    
# When an animal is tamed.
Taming:
  '1':
    Message: You tamed your first animal!
    Name: Tamer
    
# When a potion is brewed.
Brewing:
  '1':
    Message: You brewed your first potion!
    Name: Alchemist
    
# When a firework is launched.
Fireworks:
  '10':
    Message: You launched 10 fireworks!
    Name: Pyrotechnist
    
#===========================OOO=OOO===========================#
# VI-------------------------------------------------------VI #
# |                  Command achievements                   | #
# 6---------------------------------------------------------6 #
#===========================ooo=ooo===========================#
    
# Let achievement commands be given several times.
MultiCommand: true
    
# A player with achievement.give (or the console) can use the /aach give yourAch1 playerName 
# to give yourAch1 achievement to playerName.
Commands:
  yourAch1:
    Message: You took part in the special event!
    Name: Special Event Achievement!